# Generated by Django 4.0.1 on 2022-02-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('makeup', '0002_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
